### ISSUE TITLE
Win10 errors after a while

### ISSUE THREAD

**Issue by larena1** [itchyny/volume-go#11] opened 2020-06-28 18:22 UTC
I'm fetching mute status every 10 seconds and report it via MQTT. This does work fine but will fail after a while.

The first error translates to CoInitialize has not been called.

```
2020/06/25 15:31:58 MQTT connected
2020/06/26 16:47:48 GetMuted err CoInitialize wurde nicht aufgerufen.
2020/06/26 16:47:58 GetMuted err Unzulässige Funktion.
2020/06/26 16:48:38 GetMuted err Unzulässige Funktion.
2020/06/26 17:15:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:16:29 GetMuted err Unzulässige Funktion.
2020/06/26 17:17:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:17:59 GetMuted err Unzulässige Funktion.
2020/06/26 17:19:09 GetMuted err Unzulässige Funktion.
2020/06/26 17:20:09 GetMuted err Unzulässige Funktion.
2020/06/26 17:20:19 GetMuted err Unzulässige Funktion.
2020/06/26 17:21:29 GetMuted err Unzulässige Funktion.
2020/06/26 17:21:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:21:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:21:59 GetMuted err Unzulässige Funktion.
2020/06/26 17:29:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:30:29 GetMuted err Unzulässige Funktion.
2020/06/26 17:30:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:31:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:32:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:32:59 GetMuted err Unzulässige Funktion.
2020/06/26 17:33:09 GetMuted err Unzulässige Funktion.
2020/06/26 17:35:19 GetMuted err Unzulässige Funktion.
2020/06/26 17:35:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:35:59 GetMuted err Unzulässige Funktion.
2020/06/26 17:36:19 GetMuted err Unzulässige Funktion.
2020/06/26 17:36:29 GetMuted err Unzulässige Funktion.
2020/06/26 17:36:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:37:19 GetMuted err Unzulässige Funktion.
2020/06/26 17:37:39 GetMuted err Unzulässige Funktion.
2020/06/26 17:37:49 GetMuted err Unzulässige Funktion.
2020/06/26 17:38:19 GetMuted err Unzulässige Funktion.
2020/06/26 17:38:29 GetMuted err Unzulässige Funktion.
2020/06/26 17:38:39 GetMuted err Unzulässige Funktion.
```

**Comment by itchyny** [comment] 2020-06-28 20:04
I don't have Windows so can't reproduce, but patches welcome.

**Comment by larena1** [comment] 2020-06-28 20:25
I have no idea at all why this happens. As you can see, it starts happening after more than one day with consecutive calls every ten seconds.

It might've something to do with that you are recreating all the objects on every call. Maybe store objects which can be reused instead of reinitializing them always? Just a wild guess though.

**Comment by itchyny** [comment] 2020-06-29 06:59
Please create a minimal reproducible code. Does it always reproducible? I mean it sometimes runs over three or four days or it always runs into this error state after one day? Please confirm with calling `runtime.LockOSThread()` on initialization.

**Comment by larena1** [comment] 2020-06-29 12:25
> Please create a minimal reproducible code.

Should be as simple as:

```
for true {
    volume.GetMuted()
    time.Sleep(10 * time.Second)
}
```

> Does it always reproducible? I mean it sometimes runs over three or four days or it always runs into this error state after one day?
Yes, but time seems pretty random.

```
2020/06/24 23:39:20 Start
2020/06/26 16:47:48 GetMuted err CoInitialize wurde nicht aufgerufen.


2020/06/28 17:06:08 Start
2020/06/29 04:36:28 GetMuted err CoInitialize wurde nicht aufgerufen.
```

> Also, please confirm it fixes with calling `runtime.LockOSThread()` on initialization, or not.

Lock -> GetMuted -> Unlock?

**Comment by itchyny** [comment] 2020-07-07 01:44
There is unlikely some proper solution I can take here so closing for now. Feel free to write what you find to this thread.

**Closed by itchyny** 2020-07-07 01:44 UTC
